// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPYFrCfbgYxYuC7_AOL9nFUqxHQZ6MoCY',
    appId: '1:293273470582:web:840a9be47e293f81b50157',
    messagingSenderId: '293273470582',
    projectId: 'your-flutter-c5a85',
    authDomain: 'your-flutter-c5a85.firebaseapp.com',
    storageBucket: 'your-flutter-c5a85.appspot.com',
    measurementId: 'G-87EEJ2BSHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTz4dWVx10Zkya-bpLUyR21jjpvmOq2eM',
    appId: '1:293273470582:android:bfb94768f6fc9711b50157',
    messagingSenderId: '293273470582',
    projectId: 'your-flutter-c5a85',
    storageBucket: 'your-flutter-c5a85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1-vu4Pownii8U5PRwWtTEpvTYqcDH2y4',
    appId: '1:293273470582:ios:208c5bfa5497d705b50157',
    messagingSenderId: '293273470582',
    projectId: 'your-flutter-c5a85',
    storageBucket: 'your-flutter-c5a85.appspot.com',
    iosClientId: '293273470582-vmludb8lqqbi79qkhulpq4roadulrtvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1-vu4Pownii8U5PRwWtTEpvTYqcDH2y4',
    appId: '1:293273470582:ios:208c5bfa5497d705b50157',
    messagingSenderId: '293273470582',
    projectId: 'your-flutter-c5a85',
    storageBucket: 'your-flutter-c5a85.appspot.com',
    iosClientId: '293273470582-vmludb8lqqbi79qkhulpq4roadulrtvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutter',
  );
}
